repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy

