[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "C90", "NPY", "PD", "RUF"]
ignore-init-module-imports = true

[tool.ruff.format]
quote-style = "double"

[tool.mypy]
files = ["src"]
ignore_missing_imports = true
disallow_untyped_defs = true
warn_unused_ignores = true
show_error_codes = true
