name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dev dependencies
        run: pip install -r requirements-dev.txt
      - name: Ruff lint
        run: ruff check .
      - name: Ruff format
        run: ruff format . --check
      - name: Mypy
        run: mypy .
